### ISSUE TITLE
LOGO需要update，SDIM已经似了(

### ISSUE THREAD

**Issue by Kannospark** [squarezhong/SUSTech-Automation#7]

**Comment by squarezhong** [comment]
Please provide new logo file in `.svg` format, I can't find it :(

**Comment by squarezhong** [comment]
High-re

> Please provide new logo file in `.svg` format, I can't find it :(

High resolution `.png` or `.jpg` file is also OK.

**Comment by squarezhong** [comment]
logo has been updated.

**Comment by squarezhong** [comment]
logo has been updated.
